version: "27.5.1"

services:
 mongo: mongo:latest
 container_name: some-mongod
 restart: always
 environmet:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: root 
 ports:
 - 27017:27017